Improve message on base image change

diff --git a/tests/snapshot b/tests/snapshot
--- a/tests/snapshot
+++ b/tests/snapshot
@@ -1,5 +1,11 @@
 #!/bin/bash
 
+ERROR_BASE="
+Base image has changed, aborting.
+Fix by recreating the sandbox with:
+  make reset
+"
+
 function snapshot()
 {
     local cmd=$1
@@ -10,8 +16,8 @@ function snapshot()
             if [ -n "${RPMBASE}" ]; then
                 if [ -f $1/base ]; then
                     if [ "$(cat $1/base)" != "${RPMBASE}" ]; then
-                        echo "Image changed!"
-                        exit 0
+                        echo "$ERROR_BASE" >&2
+                        exit
                     fi
                 else
                     echo "${RPMBASE}" > $1/base
